# Generated by Django 5.1 on 2024-09-04 04:04

import django.core.validators
import django.db.models.deletion
import etica_y_valores.complaints.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', etica_y_valores.complaints.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enterprise_relation', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('city', models.CharField(max_length=70, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('business_unit', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('place', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('names_involved', models.TextField()),
                ('report_classification', models.CharField(max_length=70, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('detailed_description', models.TextField()),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('communication_channel', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, validators=[etica_y_valores.complaints.models.validate_custom_email])),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files/')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_type', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
