# Generated by Django 4.2.9 on 2024-09-26 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaintmodel'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaintmodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.channelcategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.citycategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='classification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.classificationcategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='enterprise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisemodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='priority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.prioritycategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='relation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.relationcategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.statuscategorymodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='complaint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaintmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
